export const onboarding_content = ["August 9, 2022 the day on which I started my journey in MBRDI as Graduate Engineering Trainee. Intially I was have 3 days Star Onboarding session to get familiarize to the MB Family, where the MB team conducted many sessions that include knowing department, Finance sessions and HR sessions.", "And also we were given a task to make Short video on past, present and future plans of MB, In which we were teams of 10 and I was not knowing any one of them. there were hurdles but in a group I successfully algined with them and made the task."]

export const Team_content = ["So after Onboarding sessions we have been alloted to the teams on which We will be working on. I have been placed in the analytics domain under Sandeep and Bibin. After getting in to the team we have attended many sessions to get the knowledge on the workflow and to understand the structure of the team, sessions include Tech Friday session, Spectrum session, Town Halls.", "Then I got Onborded to the team in which I will be working on 'AAF(Automated Analytics Framework)'. this team is building the Frontend for the extollo platform. The platform is still in building process so I will get to learn a lot in this. If it is already deployed then the hurdles will be less and also learning.So I am glad to be in this team."]

export const Certificate_content = ["After getting into team, Bibin gave us Onboarding learning tasks based on our Team requirements that has helped me a lot to understand the tools and technologies that are being used by our team. And to properly understand the code workflow that our team has developed. These tasks and courses includes AZ-900, DP-900, AKS Training Python Hackerrank problem solving, Git and Github courses, Reactjs, Flask and FastAPI courses, KT of Pipelines. These courses and Tasks Helped me a lot in initial days."]

export const Event_content = ["Attended TechCARnival, this is the first and I experienced Mercedes car, i was soo excited to drive it for the first time. It was really fun to drive S-Class and even V-Class was really amazing. I should tell I am really lucky to drive Mercedes, because so many of my colleagues didn't get chance to drive, and even they didn't get chance to experience as a passenger also.", " And another event I attended was Department outing, It was really fun and enjoyable. In the starting team building activities were really amazing, these helped me to know so many people whom I was not knowing earlier."]

export const Goal_content = ["In Future I like to contribute more on AAF tasks on my own, I should show my presence in team with my work, Nowadays I have started taking stories on my own. With the help of other developers I am finishing it. I should learn so many thing. I should not be dumb when others are talking about some tools and technologies, even I should contribute in that."]

export const Fomo_content = ["Ahh this is the tasks I was in need of, because this helped me to learn almost all tech stacks that are being used by my team, like React,Fast API, Git etc. so this helped me to understand clearly about the code workflow that my team has built. And it also helped me to understand working in team and the Agile Practices."]